updated distribution

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -39,8 +39,10 @@ jobs:
           fi
           # Loop through all gradlew scripts found and build each one
           for GRADLEW in $GRADLEWS; do
+              DIRECTORY=$(dirname $GRADLEW)
+              cd $DIRECTORY
               echo "Building $GRADLEW"
-              $GRADLEW clean build --stacktrace && echo "Build passed" || echo "Build failed"
+              gradlew clean build --stacktrace && echo "Build passed" || echo "Build failed"
           done
 
       - name: Run Tests
@@ -52,8 +54,10 @@ jobs:
           fi
           # Loop through all gradlew scripts found and test each one
           for GRADLEW in $GRADLEWS; do
+              DIRECTORY=$(dirname $GRADLEW)
+              cd $DIRECTORY
               echo "Testing $GRADLEW"
-              $GRADLEW test --stacktrace && echo "Test passed" || echo "Test failed"
+              gradlew test --stacktrace && echo "Test passed" || echo "Test failed"
           done
 
 
